### ISSUE TITLE
view rendered pull requests?

### ISSUE THREAD

**Issue by zkamvar** [NESCent/popgenInfo#140]
For @hlapp,

I'm wondering if there is the possibility of displaying the renderings of the various pull requests. A process like this would immensely aid peer review as the reviewers would not have to fork and render the document themselves. I know this may not be possible due to the way things are deployed.

**Comment by hlapp** [comment]
So, the tests render the vignettes already anyway. The issue is to put them in a place where they can be viewed in a browser. Some thoughts:

1. Viewable in browser from local files. Would require putting the rendered site on a special branch or tag, from where it can be downloaded, unpacked, etc. Still quite a few steps on the user's end, and will lead to a proliferation of branches or tags in the absence of a mechanism that cleans them up, too. Even with that on hand, to be sustainable (= not lead to repo bloat) this would have to assume that Github garbage-collects commits, so that deleting tags/branches will also eventually get rid of the commits only reachable from them, too.
2. Viewable in browser from a server. Would require either putting each successful test result on a separate directory on the gh-pages branch, or a server in addition to Github Pages. The former would quickly lead to repo bloat (lots of binary files added and deleted repeatedly) and doesn't sound sustainable to me. The latter needs a server that someone runs that we can upload to from CircleCI.
