### ISSUE TITLE
Section titles

### ISSUE THREAD

**Issue by zkamvar** [NESCent/popgenInfo#4]
Proposed menu buttons:

(text in parentheses) indicate where the link goes.

- For Users
    - Getting Started with R 
    - [pagebreak]
    - SNP (index page)
    - Microsatellites (index page)
    - Sequence (index page)
- For Developers (index page)
- For Contributors
    - How to use git
    - contributing data sets
    - contributing documents

**Comment by hlapp** [comment]
I suggest to limit hierarchical structure and index organization to the extent it is useful for navigation and conveying content clearly. Mostly empty index pages (because there are few entries yet) make the site appear less rich in content than it is. See #16 for a correspondingly motivated change of the menus.

Once there is more content than can well be navigated through the menus, we can come back to index pages. Or, if there is considerably more to go on an index page than links to vignettes.

**Comment by zkamvar** [comment]
I agree that the sparsely filled index pages will shine a somewhat negative light on the site, but I believe we were planning on filling out these index pages with our initial biological questions and linking the ones that have yet to be addressed. Once we have obtained a mass of invited submissions, then we would be able to announce it to the public. 

At least that's the way I had it in my head.

**Comment by mgiresi** [comment]
This all sounds good to me. I will be MIA until probably Friday.

**Comment by zkamvar** [comment]
I believe this issue has rendered itself useless. Closing.
