### ISSUE TITLE
Is it necessary for contributors to create a new branch on their fork?

### ISSUE THREAD

**Issue by zkamvar** [NESCent/popgenInfo#80]
I believe we have this step for those who are able to access the repository, but for those who fork the repository, it seems superfluous to create a new branch. Having them work on the master branch of their fork additionally makes it easier for them to keep up to date with just:

```
git fetch
git merge upstream/master
```

What do you think @hlapp?

**Comment by hlapp** [comment]
I don't think so. Let's consider two goals behind updating from upstream.

1. You want to keep up with the upstream master branch of stable build-passing development. Your command sequence is the way to do that, but it would be whether your own development is on master or on a branch. Worse yet, because now you have your own changes under development sitting on the same branch as changes going in from everyone (and everywhere) else, there's a higher chance you get a merge conflict, and because that's now in your fork, no one can tackle that on your behalf (unless they fork your fork). In the best case if there are no merge conflicts, you get these additional merge commits that nobody else has, because you have changes sitting in your master branch that aren't in upstream's master (yet). In your next pull request they will come along to the upstream repo even if their effective code diff is zero. (There is a way to avoid that with rebasing on upstream instead of merging, but you didn't want to make that part of the official guidelines to Git/Github novices, right?)

2. You want to pull changes from upstream in an attempt to fix up your development (because, for example, someone else's change fixes a problem you were encountering in your own development). If your development is on master, it will require advanced git fu (cherry-picking from a remote branch, for example) if there other changes on upstream that happen to conflict with yours. If your development is a branch, the only change needed to the above is first checking out that branch (which, if you are actively working on stuff, will likely be the one checked out already), and then replacing 'master' in the `git merge` command with whatever the branch upstream is (which presumably some helpful person created on upstream from your pull request to then add fix-ups).

I've seen people work on master only to get hit with merge conflicts. Then it can get pesky, and now you're mostly on your own.

**Comment by zkamvar** [comment]
I don't think I follow. Our guidelines specify to contribute via forking the repository. It seems that all of these issues you've laid out would occur even if you were developing on a separate branch in your fork. Are you suggesting that contributors not update their fork and make pull requests with an outdated version?

**Comment by hlapp** [comment]
> It seems that all of these issues you've laid out would occur even if you were developing on a separate branch in your fork. Are you suggesting that contributors not update their fork and make pull requests with an outdated version?

No they would not occur if you develop on a separate branch. Why did you think they would? If you never touch the master branch in your repo other than by updating from remote, you can't have merge conflicts, no? So perhaps you mean something else?

**Comment by zkamvar** [comment]
> If you never touch the master branch in your repo other than by updating from remote, you can't have merge conflicts, no?

This is very true. Is this the process you are envisioning?:

 - fork repository
 - create `origin/new_branch` on fork
 - work on `origin/new_branch` 
 - update `origin/master` from `NESCent/master`, but continue working on `origin/new_branch`
 - make a pull request to `NESCent/master` from `origin/new_branch` when finished

Please correct me if this is not the proper flow. If this is the proper flow, then the new branch will be based off of an old master and would potentially encounter merge conflicts on the pull request. Is that the point? is it up to us to fix those merge conflicts?

**Comment by hlapp** [comment]
> * update origin/master from NESCent/master, but continue working on origin/new_branch

Just a comment that this update will obviously not change what's going on in _new_branch_.

> Please correct me if this is not the proper flow.

I would have put the update of master only *after* the PR was made and merged.

> If this is the proper flow, then the new branch will be based off of an old master and would potentially encounter merge conflicts on the pull request. 

Yes.

> is it up to us to fix those merge conflicts?

I don't think we can ask prospective contributors for whom the workflow is already a learning experience by itself to also solve merge conflicts. This is often handled differently in other efforts with community contribution, including non-coding ones (such as Software Carpentry and Data Carpentry lessons), but it seems to me we can't expect that expertise from the typical contributor. And I'd gladly take a developed vignette in exchange for resolving some merge conflicts.

**Comment by zkamvar** [comment]
> I would have put the update of master only after the PR was made and merged.

I think therein was the source of my confusion. I was assuming that the owners of the forks needed to keep their branches up to date before they merged. I can see that this would put the burden of the merge conflicts on them. If they make a PR from an old branch and there are merge conflicts, we can fix these on our local machines and then merge.

Thank you for clarifying, Hilmar.

**Comment by zkamvar** [comment]
And now I realize why this is a good thing. This would allow one to create multiple branches that can serve different purposes that can be developed at different times.
